name: CI
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node
      - run: pnpm check-style

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node
      - run: pnpm lint

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lib
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node
      - run: pnpm test

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lib
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node
      - run: pnpm build

  release:
    # needs: [check-style, lint, test, build]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lib
    # if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node
        with:
          node-version: 18.x
      - run: pnpm exec nx reset
      - run: pnpm exec nx run my-app:semantic-release --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
